# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contact_name', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('contact_email', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('contact_type', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('contact_content', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contact_email', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
            ],
        ),
    ]
