# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='contact_type',
        ),
    ]
