# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_contactinfo_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contact_is_detail',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_is_partner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_is_product',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
