# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revisited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('url', models.CharField(db_index=True, max_length=2000)),
                ('details', jsonfield.fields.JSONField(blank=True, db_index=True, null=True)),
                ('parse_state', models.PositiveIntegerField(db_index=True, default=100)),
            ],
        ),
    ]
