# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldetails',
            old_name='url',
            new_name='social_id',
        ),
        migrations.AddField(
            model_name='urldetails',
            name='source_type',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
