# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20170613_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLDetails',
            new_name='SocialDetails',
        ),
    ]
