# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20170613_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='url_after_req',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
