# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_socialdetails_url_after_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialdetails',
            name='details',
        ),
    ]
