# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:12
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_remove_socialdetails_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
