# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_auto_20170613_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialdetails',
            name='revisited_at',
        ),
    ]
