# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0008_remove_socialdetails_revisited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
    ]
