# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0009_socialdetails_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdetails',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
