# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0010_auto_20170613_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='ins_biography',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_external_url',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_follower_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_following_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_fullname',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_id',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_post_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ins_recent_12_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='social_media_type',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_business',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_country',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_description',
            field=models.CharField(blank=True, db_index=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_related_links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_subscribers',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_username',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialdetails',
            name='ytb_views',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
