# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0011_auto_20170705_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('social_media_type', models.CharField(db_index=True, max_length=20)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True)),
                ('url', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_fullname', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_id', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_follower_count', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ins_following_count', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ins_post_count', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ins_biography', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_external_url', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_recent_12_meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True)),
                ('ins_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True)),
                ('ytb_username', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ytb_subscribers', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ytb_views', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('ytb_description', models.CharField(blank=True, db_index=True, max_length=3000, null=True)),
                ('ytb_business', models.BooleanField(db_index=True, default=False)),
                ('ytb_country', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ytb_related_links', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_biography',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_external_url',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_follower_count',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_following_count',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_fullname',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_id',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_json',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_post_count',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ins_recent_12_meta',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='social_media_type',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_business',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_country',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_description',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_related_links',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_subscribers',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_username',
        ),
        migrations.RemoveField(
            model_name='socialdetails',
            name='ytb_views',
        ),
    ]
