# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0013_auto_20170706_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialtracking',
            old_name='ins_post_count',
            new_name='ins_media_count',
        ),
        migrations.AddField(
            model_name='socialtracking',
            name='ins_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socialtracking',
            name='ins_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
