# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 20:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0014_auto_20170707_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtracking',
            name='ins_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialtracking',
            name='ins_recent_12_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
