# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0015_auto_20170707_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsSimilarPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('re_visited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ins_url', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('ins_similar_people', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
