# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0016_inssimilarpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtracking',
            name='ins_url_id',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
