# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0017_socialtracking_ins_url_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialtracking',
            old_name='ins_url_id',
            new_name='ins_username',
        ),
    ]
