# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0018_auto_20170710_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtracking',
            name='ins_find_similar',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
