# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0019_socialtracking_ins_find_similar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsSimilarPeople',
            new_name='ProcessInstagram',
        ),
    ]
