# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0020_auto_20170823_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialtracking',
            old_name='url',
            new_name='profile_url',
        ),
        migrations.RemoveField(
            model_name='processinstagram',
            name='ins_similar_people',
        ),
        migrations.RemoveField(
            model_name='socialtracking',
            name='social_media_type',
        ),
        migrations.RemoveField(
            model_name='socialtracking',
            name='tags',
        ),
        migrations.AddField(
            model_name='processinstagram',
            name='ins_find_similar',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='processinstagram',
            name='ins_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
    ]
