# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0021_auto_20170823_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinstagram',
            old_name='re_visited_at',
            new_name='last_visited_at',
        ),
        migrations.AddField(
            model_name='processinstagram',
            name='last_follower_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
