# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0022_auto_20170823_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessInstagram',
            new_name='InstagramMap',
        ),
        migrations.RenameModel(
            old_name='SocialTracking',
            new_name='InstagramTracking',
        ),
    ]
