# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0023_auto_20170823_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeDetails',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_business',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_country',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_description',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_related_links',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_subscribers',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_username',
        ),
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ytb_views',
        ),
        migrations.AlterField(
            model_name='instagrammap',
            name='last_visited_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
