# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0024_auto_20170825_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramtracking',
            name='ins_find_similar',
        ),
    ]
