# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0025_remove_instagramtracking_ins_find_similar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrammap',
            old_name='ins_url',
            new_name='ins_id',
        ),
        migrations.RenameField(
            model_name='instagrammap',
            old_name='last_follower_count',
            new_name='latest_follower_count',
        ),
        migrations.RenameField(
            model_name='instagrammap',
            old_name='last_visited_at',
            new_name='latest_visited_at',
        ),
        migrations.AddField(
            model_name='instagrammap',
            name='latest_username',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
