# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0027_auto_20170825_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammap',
            name='latest_crawl_state',
            field=models.PositiveIntegerField(db_index=True, default=200),
        ),
    ]
