# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 17:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0028_instagrammap_latest_crawl_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammap',
            name='ins_growth',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrammap',
            name='ins_growth_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammap',
            name='latest_crawl_state',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
