# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0029_auto_20170908_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammap',
            name='project_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
