# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 04:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0031_auto_20170930_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('rating', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('reviews', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('memo', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
