# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0032_googlemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemap',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
