# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0033_googlemap_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlemap',
            old_name='memo',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='googlemap',
            old_name='cid',
            new_name='map_url',
        ),
        migrations.AddField(
            model_name='googlemap',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
