# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0035_googlemap_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlemap',
            name='rating',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='googlemap',
            name='reviews',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
