# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0036_auto_20171026_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlemap',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='googlemap',
            name='reviews',
        ),
    ]
