# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0037_auto_20171026_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemap',
            name='rating',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='googlemap',
            name='reviews',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
