# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revisited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('gym_name', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('street_address', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('hours', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('holiday', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('gym_url', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
                ('employment', models.CharField(blank=True, db_index=True, max_length=2000, null=True)),
            ],
        ),
    ]
